# Generated by Django 4.0.5 on 2022-07-03 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'),), 'verbose_name': 'Книжный экземпляр', 'verbose_name_plural': 'Книжные экземпляры'},
        ),
    ]
